/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2018-09-10 06:44:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"ja\">\n");
      out.write("  <head>\n");
      out.write("    <!-- Required meta tags -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/main.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/responsive.css\">\n");
      out.write("\n");
      out.write("    <!-- Font-Awesome -->\n");
      out.write("    <link href=\"https://use.fontawesome.com/releases/v5.0.6/css/all.css\" rel=\"stylesheet\">\n");
      out.write("    <title>BookShare!!</title>\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("    <div id=\"main-wrapper\">\n");
      out.write("        <!-- header -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("      <main>\n");
      out.write("        <!--  top-wrapper  -->\n");
      out.write("        <div class=\"jumbotron text-center\" id=\"masthead\">\n");
      out.write("          <div class=\"wrapper\">\n");
      out.write("            <h1>\n");
      out.write("              Book That Changed <br>\n");
      out.write("              Your Life\n");
      out.write("            </h1>\n");
      out.write("            <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary btn-lg\" id=\"masthead-btn\"><span id=\"btn-text\">投稿を見る</span></button>\n");
      out.write("            <p class=\"small\">Find your best book that will help change your life.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!--  features-wrapper  -->\n");
      out.write("        <div class=\"features-wrapper mb-5\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"features-title my-5 text-center\">\n");
      out.write("               <h2 id=\"title\" class=\"my-3\">BookShareとは</h2>\n");
      out.write("               <h4 class=\"conatainer-text\" id=\"features-des\">\n");
      out.write("                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.\n");
      out.write("              </h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row text-center my-4\">\n");
      out.write("              <div class=\"col-md-4\">\n");
      out.write("                <i class=\"fas fa-book fa-6x my-5\"></i>\n");
      out.write("                <h4>特徴</h4>\n");
      out.write("                <p class=\"my-4 conatainer-text\">Lorem ipsum dolor sit amet, consectetuer adipiscing elit,\n");
      out.write("                sed diam nonummy nibh euismod tincidunt ut laoreet dolore\n");
      out.write("                magna aliquam erat volutpat. </p>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-md-4\">\n");
      out.write("                <i class=\"fas fa-check fa-6x my-5\"></i>\n");
      out.write("                <h4>ミッション</h4>\n");
      out.write("               <p class=\"my-4 conatainer-text\">Lorem ipsum dolor sit amet, consectetuer adipiscing elit,\n");
      out.write("                sed diam nonummy nibh euismod tincidunt ut laoreet dolore\n");
      out.write("                magna aliquam erat volutpat. </p>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-md-4\">\n");
      out.write("                <i class=\"fas fa-history fa-6x my-5\"></i>\n");
      out.write("                <h4>設立経緯</h4>\n");
      out.write("                <p class=\"my-4 conatainer-text\">Lorem ipsum dolor sit amet, consectetuer adipiscing elit,\n");
      out.write("                sed diam nonummy nibh euismod tincidunt ut laoreet dolore\n");
      out.write("                magna aliquam erat volutpat. </p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"text-center conatainer-text mb-5\">\n");
      out.write("                <p>詳細につきましてはこちらの<span><a href=\"\">ブログ</a></span>をご参照ください。</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!--  contents-wrapper  -->\n");
      out.write("        <div class=\"contents-wrapper\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"contents-title text-center\">\n");
      out.write("              <h2 id=\"title\" class=\"my-3\">投稿を見る</h2>\n");
      out.write("               <h4 class=\"conatainer-text\" id=\"contents-des\">\n");
      out.write("                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. </h4>\n");
      out.write("                <h5>最新の投稿</h5>\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-dark btn-lg contents-btn\" id=\"contents-btn\"><span id=\"btn-text\">投稿一覧へ</span></button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!--  signin-wrapper  -->\n");
      out.write("        <div class=\"signup-wrapper\">\n");
      out.write("          <div class=\"container text-center\">\n");
      out.write("            <div class=\"signin-title\">\n");
      out.write("              <h2 id=\"title\" class=\"mb-4\">無料会員登録</h2>\n");
      out.write("              <h4 class=\"conatainer-text\">\n");
      out.write("                Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed diam nonummy\n");
      out.write("                nibh euismod tincidunt ut laoreet. </h4>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-dark btn-lg\" id=\"signin-btn\"><span id=\"btn-text\">無料会員登録へ</span></button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </main>\n");
      out.write("      <!--  footer  -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- Optional JavaScript -->\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
